<?php 
//;$Id$

function deductible_menu(){
$items['deductible/calculate']=array(
'title'=>'Calculate Deductible',
'page callback'=>'drupal_get_form',
'page arguments'=>array('deductible_simple_form'),
'access arguments' => array('administer user'),
);
return $items;
}

function deductible_simple_form($form,&$form_submit){
      $form['Make'] = array(
        '#type' => 'textfield',
        '#title' => t('Make'),
          '#cols' => 30,
           '#rows' => 1,
      );
        $form['Model'] = array(
        '#type' => 'textfield',
        '#title' => t('Models'),
          '#cols' => 30,
        '#rows' => 1,
      );
	 
	 $form['checkbox1'] = array(
	  '#type' =>'checkbox', 
	  '#title' => t('Send me a copy!'),
	  
	  );
	  
	    $form['keywords'] = array(
		'#title' => t('Keywords'),
		'#type' => 'textarea','#description' => t
			('Example: funny, bungee jumping, "Company, Inc."'),
		'#default_value' => isset(  $context['keywords']) ? drupal_implode_tags($context['keywords']) : '',
	);
	   
	  $form['selected'] = array(
       '#type' => 'select',
       '#title' => t('Selected'),
       '#options' => webform_options_countries(),
     );

	    
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
       '#submit' => array('deductible_submit'),
      
      );
	  
	 return $form;
}

/**
 * Implements hook_webform_select_options_info().
 */
/*function deductible_webform_select_options_info() {

  $items = array();
  $items['countries'] = array(
    'title' => t('Countries'),
    'options callback' => 'webform_options_countries',
  );
  return $items;
}*/

/**
 * Webform options info callback.
 */
function webform_options_countries() {
  
  $forms = array(
    t('Europe') => array (
      'nl' =>  t('The Netherlands'),
      'be' =>  t('Belgium'),
      'fr' =>  t('France'),
    ),
    t('Africa') => array (
      'tu'  =>  t('Tunisia'),
      'sa'  =>  t('South Africe'),
    ),
    t('Asia') => array (
      'ru'  =>  t('Russia'),
      'cn'  =>  t('China'),
    ),
    'key' => t('some country that is in no group'),
  );
  return $forms;
}

/**
 * Implementation of hook_perm().
 */
function deductible_perm() {
  return array('use save and edit', 'administer save and edit');
}

function deductible_submit($form, &$form_values){
      watchdog('Deductibe', 'deductible', array(), WATCHDOG_DEBUG);
      $message = 'You have submitted the ' /*. $form_id . ' form which contains the following data:<pre>' . print_r($form_values,true) . '</pre>'*/;
      drupal_set_message(t($message));
    }
